source 'https://rubygems.org'

gem 'rails'
gem 'jquery-rails'
gem 'haml-rails'
gem 'unicorn'
gem 'devise'
gem 'wicked'
gem 'gmaps4rails'
gem 'geocoder'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'twitter-bootstrap-rails'
gem 'pg'
gem 'dragonfly'
gem 'rack-cache'
gem 'fog'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'less-rails'
  gem 'uglifier', '>= 1.0.3'
end
