Infinity = 1.0 / 0

TRANSACTION_PRE_AUTHORIZATION_REQUIRED = 'Pre authorization required'
TRANSACTION_HOST_CONFIRMATION_REQUIRED = 'Host confirmation required'
TRANSACTION_FINISHED = 'transaction finished'

BOOKING_STATUS_FINISHED = 'finished'
BOOKING_STATUS_UNFINISHED = 'unfinished'
BOOKING_STATUS_REJECTED = 'rejected'
BOOKING_STATUS_GUEST_CANCELED = 'guest_canceled'
BOOKING_STATUS_HOST_CANCELED = 'host_canceled'
HOST_HAS_REQUESTED_CANCELLATION = 'host_requested_cancellation'
BOOKING_STATUS_HOST_PAID = 'host paid'

PERSONALITIES = [
  'Barker', 'Digger', 'Chewer', 'Playful', 'Energetic', 'Mellow', 'Smart',
  'Obedient', 'Mischievous', 'Loud', 'Quiet', 'Protective', 'Affectionate',
  'Crazy', 'Independent', 'Rowdy', 'Calm', 'Athletic', 'Lively', 'Happy',
  'Gentle'
]
DOG_BREEDS = [
  "Affenpinscher", "Afghan hound", "Airedale Terrier", "Akita",
  "Alaskan malamute", "Alsatian", "American cocker", "American Cocker Spaniel",
  "American eskimo dog", "American foxhound", "American Staffordshire Terrier",
  "Anatolian karabash", "Australian Bull Dog", "Australian Shepherd",
  "Australian Shepherd X", "Australian Terrier", "Australian Terrier X",
  "Basenji/Lab X", "Bassett Hound", "Beagle", "Beagle X", "Beagle/Cavi X",
  "Beaglier", "Bearded Collie", "Bedlington Terrier", "Belgian griffon",
  "Bergamasco", "Bernese Mountain Dog", "Bichon Frise", "Bichon Frise X",
  "Bichon Frise/Maltese X", "Bichon Frise/Mini Schnauzer",
  "Bichon Frise/Shih Tzu X", "Bichon/Cavi X", "Bichon/Poodle X", "Bloodhound",
  "Blue Heeler", "Blue Heeler/Border Collie X", "Blue Heeler/Jack Russell X",
  "Blue Heeler/Kelpie X", "Blue Heeler/Saffordshire X", "Bluetick Coonhound",
  "Bolognese", "Border Collie", "Border Collie X",
  "Border collie/Blue heeler X", "Border Collie/Kelpie X",
  "Border Collie/Sheltie X", "Border Collie/Spaniel X", "Border Terrier",
  "Borzoi", "Boston terrier", "Boxer", "Boxer Labrador X", "Boxer X",
  "Boxer/Ridgeback X", "Boxer/Staffy X", "Bracco", "Briard", "British Bulldog",
  "Brittany Spaniel", "Buhund", "Bull Arab", "Bull Arab/Collie X",
  "Bull Terrier", "Bull Terrier (miniature)", "Bull Terrier X",
  "Bull Terrier/Blue heeler X", "Bull Terrier/Mastiff X", "Bulldog",
  "Bullmastiff", "Cairn Terrier", "Canaan", "Cattle Dog/Pointer X",
  "Cavalier King Charles Spaniel", "Cavalier X", "Cavalier/Beagle X",
  "Cavalier/Maltese X", "Cavalier/Poodle X", "Cavalier/Shihtzu X",
  "Cavalier/Spaniel X", "Cavalier/Tibetan Terrier X", "Cavoodle",
  "Chesapeake bay retriever", "Chihauhau X", "Chihauhau/Cavalier X",
  "Chihauhau/FoxieX", "chihauhau/Jack Russell X", "Chihauhau/Silky Terrier X",
  "Chihauhau/Terrier X", "Chihauhua", "Chihuahau/Pomeranian X",
  "Chihuahua/Australian Terrier X", "Chin", "Chinese Chested", "Chow Chow",
  "Chow Retriever X", "Clumber spaniel", "Cocker Spaniel",
  "Cocker Spaniel (American)", "Cocker Spaniel (Black)",
  "Cocker Spaniel (Blue Roan)", "Cocker Spaniel (Golden)",
  "Cocker Spaniel (Red White)", "Cocker Spaniel Heeler X",
  "Cocker Spaniel X", "Cocker Spaniel/Cavalier X",
  "Cocker Spaniel/Jack Russell X", "Cocker Spaniel/Labrador X",
  "Cocker Spaniel/Mini Pinscher X", "Collie (Rough)", "Collie (Short Hair)",
  "Collie X", "Collie/Briard X", "Collie/Kelpie X", "Collie/Staffordshire X",
  "Corgi (cardigan)", "Corgi X", "Curly Coated Retriever", "Czesky terrier",
  "Dachshund (Long Haired)", "Dachshund (min long haired)",
  "Dachshund (min smooth haired)", "Dachshund (min Wire Haired)",
  "Dachshund (Smooth Haired)", "Dachshund (Wire Haired)", "Dalmation",
  "Dalmation/Blue Heeler X", "Dalmation/Pointer X", "Dandie dinmont",
  "Deerhound", "Dobermann", "Dobermann X", "Dogue De Bordeaux", "Elkhound",
  "English Cocker Spaniel", "English Pointer", "English setter",
  "English Springer Spaniel", "English Toy Terrier", "Eskimo dog",
  "Estrella mountain dog", "Field spaniel", "Finnish lapphund", "Finnish spitz",
  "Flat Coated Retriever", "Fox Hound", "Fox Terrier",
  "Fox Terrier (Miniature)", "Fox Terrier X", "Fox Terrier/Chihuahua X",
  "Fox Terrier/Jack Russell X", "Foxy/Border X", "French Bulldog",
  "French Bulldog (Black)", "German Shepard/Huntaway X", "German Shepherd",
  "German Shepherd (white)", "German Shepherd X", "German Shepherd?Dobermann X",
  "German Shorthaired Pointer", "German spitz", "German wire haired pointer",
  "Giant Schnauzer", "Glen of imaal terrier", "Golden Retriever",
  "Golden Retriever/Cocker X", "Golden Retriever/German Shepherd X",
  "Golden Retriever/Labrador X", "Golden Retriever/Poodle X", "Gordon setter",
  "Grand basset griffon", "Great Dane", "Great Dane/Gernman Shepherd X",
  "Great Dane/Mastiff X", "Greyhound", "Greyhound/Whippet X",
  "Griffon Bruxellois", "Groodle", "Hamilton stovare", "Harrier", "Havanese",
  "Heeler", "Heeler X", "Heeler/Cavi X", "Heeler/Dalmation X",
  "Heeler/Kelpie X", "Heeler/Retriever X", "Heeler/Spaniel X",
  "Heeler/Staffy X", "Hovawart", "Hungarian kuvasz", "Hungarian puli",
  "Hungarian Vizsla", "Husky/Lab X", "Ibizan", "Irish Red &amp; White Setter",
  "Irish red setter", "Irish Setter", "Irish terrier", "Irish water spaniel",
  "Irish Wolfhound", "Irish Wolfhound X", "Italian Greyhound",
  "Italian spinone", "Jack Russell", "Jack Russell (Long Haired)",
  "Jack Russell X", "Jack Russell/Border X", "Jack Russell/Chihuahua X",
  "Jack Russell/Fox Terrier X", "Jack Russell/Maltese X",
  "Jack Russell/Mini Fox Terrier X", "Jack Russell/Norfolk Terrier X",
  "Jack Russell/Pomeranian X", "Japanese Chin", "Japanese shiba inu",
  "Japanese spitz", "Keeshond", "Keeshond/Kelpie X", "Kelpie", "Kelpie X",
  "Kelpie/Border Collie X", "Kelpie/Collie X", "kelpie/German Shepherd X",
  "Kelpie/Heeler X", "kelpie/malamute X", "Kelpie/Pharoah HoundX",
  "Kelpie/Rottweiler X", "Kerry Blue Terrier", "King Charles Spaniel",
  "Kodi kerhondje", "Komondor", "Koolie", "Koolie/Border Collie X",
  "Labradoodle", "Labrador", "Labrador (Black)", "Labrador (Chocolate)",
  "Labrador (Golden)", "Labrador X", "Labrador X Wolfhound",
  "Labrador/Boarder X", "Labrador/Cocker Spaniel X",
  "Labrador/Curly Coated Retriever", "Labrador/Kelpie X", "Labrador/Pointer X",
  "Labrador/Retriever X", "Labrador/Ridgeback X", "Labrador/Shepherd X",
  "Labrador/Spaniel X", "Labrador/Staffordshire X", "Labraor/Blue Heeler X",
  "Laekondis", "Lagotto Romagnolo", "Lakeland Terrier", "Lapphund",
  "Large Munsterlander", "Leonberger", "Lhasa Apso", "Lhasa Apso X",
  "Lhasa Apso/Bichon X", "Lhasa Apso/Maltese X", "Lowchen", "Lurcher",
  "Malinois", "Maltese", "Maltese X", "Maltese/Bichon Frise X",
  "Maltese/Cavalier X", "Maltese/Cavalier/Shih Tzu X", "Maltese/Chihuahua X",
  "Maltese/Jack Russell X", "Maltese/Lhasa Apso X", "Maltese/Pekinese X",
  "Maltese/Pom X", "Maltese/Pomeranian/Shih Tzu X", "Maltese/Poodle X",
  "Maltese/Poodle/Westie X", "Maltese/Pug X", "Maltese/Shih Tzu X",
  "Maltese/Silky X", "Maltese/Terrier X", "Maltese/Westie X",
  "Maltese/Westie/Shih Tzu X", "Manchester Terrier", "Maremma", "Mastiff",
  "Mastiff X", "Mastiff/Corgi X", "Miniature Pinscher",
  "Miniature Pinscher (Red)", "Moodle", "Munsterlander", "Newfoundland",
  "Newfoundland X", "Norfolk terrier", "Norwegian buhund", "Norwegian Elkhound",
  "Norwegian lunderhund", "Norwich terrier", "Nova Scotia Duck Tolling Retriev",
  "Old English Sheepdog", "Otterhund", "PapillionxShiutzu", "Papillon",
  "Papillon/Yorkshire Terrier X", "Parson Russell Terrier", "Pekingese",
  "Pembroke corgi", "Petit Basset Griffon Vendeen", "Petit basson",
  "Pharaoh Hound", "Pointer", "Pointer X", "Pom X Fox Terrier", "Pomeranian",
  "Pomeranian X", "Pomeranian/Chihuahua X", "Poodle",
  "Poodle (Miniature Apricot)", "Poodle (Miniature Black)",
  "Poodle (Miniature)", "Poodle (Standard)", "Poodle (Standard) (Black)",
  "Poodle (Standard) (Brown)", "Poodle (Standard) (Chocolate)",
  "Poodle (Standard) (Silver)", "Poodle (Toy)", "Poodle X",
  "Poodle X (Toy Apricot)", "Poodle/Bichon X", "Poodle/Border X",
  "Poodle/Chihuahua X", "Poodle/Jack Russell X", "Poodle/Maltese X",
  "Poodle/Schnauzer X", "Poodle/Shihtzu X", "Poodle/Silky X",
  "Poodlier (poodle X cavalier)", "Portugese Water Dog", "Portuguese Podengo",
  "Pug", "Pug X", "Pug/Maltese/Shihtzu", "Pug/Sheltie X",
  "Pugalier (pug X cavalier)", "Pyrenean Mountain Dog", "Rhodesian Ridgeback",
  "Rhodesian Ridgeback X", "Rhodesian Ridgeback/Whippet X",
  "Ridgeback/Shepherd X", "Rottweiler", "Rottweiler X",
  "Rottweiler/Dobermann X", "Rottweiler/Old English X", "Saluki", "Samoyed",
  "Schipperke", "Schnauzer", "Schnauzer X (Miniature)", "Schnauzer (Giant)",
  "Schnauzer (Standard)", "Schnauzer/Bichon Frise", "Schnauzer/Shih Tzu X",
  "scottish terrier", "Scottish Terrier/Jack Russell X", "Sealyham terrier",
  "Segugio", "setter cross", "Sharpi", "Sharpi X", "Sheltie",
  "Shetland Sheepdog", "Shiba Inu", "Shih Tzu", "Shih Tzu X",
  "Shih Tzu/Bichon Frise X", "Shih Tzu/Maltese X", "Shih Tzu/Pekingese X",
  "Shih Tzu/Poodle X", "Shih Tzu/Schnauzer X", "shih Tzu/staffy X",
  "Shih Tzu/Terrier X", "Siberian Husky", "Silky Terrier", "Silky X",
  "Silky/Australian Terrier X", "Silky/Jack Russell X", "Silky/Maltese X",
  "Silky/Shihtzu X", "Silky/Yorkshire Terrier X", "Skye terrier", "Sloughi",
  "Snoodle", "Soft Coated Wheaten Terrier", "Spaniel/Bassett X",
  "Spaniel/Heeler X", "Spaniel/terrier X", "Spoodle", "Spoodle/Retriever X",
  "Springer Spaniel", "St. Bernard", "St. Bernard",
  "Staffordshire Bull Terrier", "Staffordshire Bull Terrier X",
  "Staffordshire/Labrador X", "Staffordshire/Pitbull X",
  "Staffordshire/Ridgeback X", "Staffy / German Shepherd", "Staffy X Foxy",
  "Staffy/Heeler X", "Staffy/Pointer X", "Staghound/Greyhound/Rigdeback X",
  "Sussex Spaniel", "Swedish valhund", "Tentefield Terrier", "Terrier X",
  "Terrier X Minature Pinscher", "Tervuren", "Tibetan Spaniel",
  "Tibetan Spaniel X", "Tibetan Terrier", "Tibetan X", "Weimaraner",
  "Welsh Springer Spaniel", "Welsh Springer Spaniel", "Welsh Terrier",
  "West Highland White Terrier", "West Highland X", "West Highland/Poodle X",
  "Westie/Cairn Terrier", "Wheaten Terrier (Soft Coated)", "Whippet",
  "whippet X", "White Swiss Shepherd Dog", "Wippet/Kelpie X",
  "Wolfhound/Mastiff X", "Yorkshire Terrier"
]
