---
development:
  cloud_name: hxnfgf9c2
  api_key: '174367239888482'
  api_secret: LP9JsFUvwTXSd1x5iQ8G96UZWzY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hxnfgf9c2
  api_key: '174367239888482'
  api_secret: LP9JsFUvwTXSd1x5iQ8G96UZWzY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hxnfgf9c2
  api_key: '174367239888482'
  api_secret: LP9JsFUvwTXSd1x5iQ8G96UZWzY
  enhance_image_tag: true
  static_image_support: false
staging:
  cloud_name: hxnfgf9c2
  api_key: '174367239888482'
  api_secret: LP9JsFUvwTXSd1x5iQ8G96UZWzY
  enhance_image_tag: true
  static_image_support: false
